spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/junit_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
mybatis:
  mapper-locations: classpath*:**/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: ccn.digit.batch.entity.*
